// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: messageWithCounter.proto

package messageWithCounter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Key struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_UserId int64                  `protobuf:"varint,1,opt,name=user_id,json=userId"`
	xxx_hidden_Sha256 []byte                 `protobuf:"bytes,2,opt,name=sha256"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_messageWithCounter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_messageWithCounter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Key) GetUserId() int64 {
	if x != nil {
		return x.xxx_hidden_UserId
	}
	return 0
}

func (x *Key) GetSha256() []byte {
	if x != nil {
		return x.xxx_hidden_Sha256
	}
	return nil
}

func (x *Key) SetUserId(v int64) {
	x.xxx_hidden_UserId = v
}

func (x *Key) SetSha256(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Sha256 = v
}

type Key_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	UserId int64
	Sha256 []byte
}

func (b0 Key_builder) Build() *Key {
	m0 := &Key{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_UserId = b.UserId
	x.xxx_hidden_Sha256 = b.Sha256
	return m0
}

type MessageWithCounter struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Counter uint64                 `protobuf:"varint,1,opt,name=counter"`
	xxx_hidden_Message string                 `protobuf:"bytes,2,opt,name=message"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MessageWithCounter) Reset() {
	*x = MessageWithCounter{}
	mi := &file_messageWithCounter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageWithCounter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWithCounter) ProtoMessage() {}

func (x *MessageWithCounter) ProtoReflect() protoreflect.Message {
	mi := &file_messageWithCounter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MessageWithCounter) GetCounter() uint64 {
	if x != nil {
		return x.xxx_hidden_Counter
	}
	return 0
}

func (x *MessageWithCounter) GetMessage() string {
	if x != nil {
		return x.xxx_hidden_Message
	}
	return ""
}

func (x *MessageWithCounter) SetCounter(v uint64) {
	x.xxx_hidden_Counter = v
}

func (x *MessageWithCounter) SetMessage(v string) {
	x.xxx_hidden_Message = v
}

type MessageWithCounter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Counter uint64
	Message string
}

func (b0 MessageWithCounter_builder) Build() *MessageWithCounter {
	m0 := &MessageWithCounter{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Counter = b.Counter
	x.xxx_hidden_Message = b.Message
	return m0
}

var File_messageWithCounter_proto protoreflect.FileDescriptor

var file_messageWithCounter_proto_rawDesc = string([]byte{
	0x0a, 0x18, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x57, 0x69, 0x74, 0x68, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x57, 0x69, 0x74, 0x68, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x1a, 0x21,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x67, 0x6f, 0x5f, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x44, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x05, 0xaa, 0x01, 0x02, 0x08, 0x02,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x32,
	0x35, 0x36, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x42, 0x05, 0xaa, 0x01, 0x02, 0x08, 0x02, 0x52,
	0x06, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x22, 0x56, 0x0a, 0x12, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x57, 0x69, 0x74, 0x68, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x1f, 0x0a,
	0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x05,
	0xaa, 0x01, 0x02, 0x08, 0x02, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x1f,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x05, 0xaa, 0x01, 0x02, 0x08, 0x02, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42,
	0x54, 0x5a, 0x4a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x43, 0x69,
	0x76, 0x69, 0x6c, 0x2f, 0x74, 0x67, 0x2d, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x2d, 0x72, 0x65,
	0x67, 0x65, 0x78, 0x2d, 0x61, 0x6e, 0x74, 0x69, 0x73, 0x61, 0x70, 0x6d, 0x2f, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x73, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x57, 0x69, 0x74, 0x68, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x92, 0x03, 0x05,
	0xd2, 0x3e, 0x02, 0x10, 0x03, 0x62, 0x08, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x70,
	0xe8, 0x07,
})

var file_messageWithCounter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_messageWithCounter_proto_goTypes = []any{
	(*Key)(nil),                // 0: messageWithCounter.Key
	(*MessageWithCounter)(nil), // 1: messageWithCounter.MessageWithCounter
}
var file_messageWithCounter_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_messageWithCounter_proto_init() }
func file_messageWithCounter_proto_init() {
	if File_messageWithCounter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messageWithCounter_proto_rawDesc), len(file_messageWithCounter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messageWithCounter_proto_goTypes,
		DependencyIndexes: file_messageWithCounter_proto_depIdxs,
		MessageInfos:      file_messageWithCounter_proto_msgTypes,
	}.Build()
	File_messageWithCounter_proto = out.File
	file_messageWithCounter_proto_goTypes = nil
	file_messageWithCounter_proto_depIdxs = nil
}
