edition = "2023";

package messageWithCounter;

import "google/protobuf/go_features.proto";

option features.(pb.go).api_level = API_OPAQUE;
option go_package = "github.com/Civil/tg-simple-regex-antisapm/filters/types/messageWithCounter";

message Key {
  int64 user_id = 1 [features.field_presence = IMPLICIT];
  bytes sha256 = 2 [features.field_presence = IMPLICIT];
}

message MessageWithCounter {
  uint64 counter = 1 [features.field_presence = IMPLICIT];
  string message = 2 [features.field_presence = IMPLICIT];
}
